#!/usr/bin/env bash

# Setup Script para el entorno
# Autor: Javier Rodríguez-Alarcón <javier@javierdz.dev>

# Instalar todo
# Si no esta zsh instalado, instalarlo
if [ ! -x "$(command -v zsh)" ]; then
    echo "ZSH no está instalado. Instalando..."
    # detectar gestor de paquetes y usar el adecuado
    if [ -x "$(command -v apt)" ]; then
        PKG_MANAGER="apt"
    elif [ -x "$(command -v yum)" ]; then
        PKG_MANAGER="yum"
    elif [ -x "$(command -v pacman)" ]; then
        PKG_MANAGER="pacman"
    else
        echo "No se encontró un gestor de paquetes compatible. Instala ZSH manualmente."
        exit 1
    fi
    $PKG_MANAGER update
    $PKG_MANAGER install zsh -y
fi
if [ ! -f "~/.zshrc"]; then
    echo "No tienes instalado ZSH. Instalando..."
    $PKG_MANAGER install zsh -y
fi
if [ ! -d "~/.oh-my-zsh" ]; then
    echo "No tienes instalado Oh My Zsh. Instalando..."
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi
echo "Configurando .zshrc..."
cp $PWD/.zshrc ~/.zshrc
echo "Instalando gitinit..."
cp $PWD/gitinit /usr/local/bin/gitinit
chmod +x /usr/local/bin/gitinit
chown $USER:$USER /usr/local/bin/gitinit
echo "Instalando diskutil..."
cp $PWD/diskutil /usr/local/bin/diskutil
chmod +x /usr/local/bin/diskutil
chown $USER:$USER /usr/local/bin/diskutil
echo "Setup completado. Reinicia tu terminal o ejecuta 'source ~/.zshrc' para aplicar los cambios."
exit 0